#!/usr/bin/env python

import sys;
import os;
import subprocess
import time

if not os.environ.get("TRAIN_SCH_ROOTDIR"):
	print("environment not set up")
	sys.exit(-1);

exe_name = os.environ["TRAIN_SCH_EXEDIR"] + "/train-sch"
datadir = os.environ["TRAIN_SCH_DATADIR"]

if (len(sys.argv) > 1):
	specific_dataset = sys.argv[1];

pids = set()

for ifile in os.listdir(datadir):
	if (ifile.endswith(".dot")):
		experiment_dir = "dataset-" + ifile;
		os.makedirs(experiment_dir, exist_ok=True)

		args = [ exe_name, "--data-file", datadir + "/" + ifile ]
		print(args)
		ouput_file = open(experiment_dir + "/stdout.txt", "w")
		subprocess.Popen(args, cwd=experiment_dir, stdout=ouput_file, stderr=subprocess.STDOUT);

while pids:
	pid, retval = os.wait()
	pids.remove(pid)
